### ISSUE TITLE
Error when running cannot access org.springframework.data.elasticsearch.core.query.BaseQueryBuilder

### ISSUE THREAD

**Issue by waytoharish** [aws-samples/opensearch-bootful#3]
Hi,

I am getting following error when trying to run the code

/Users/hkshar/mywork/open-search/opensearch-bootful/src/main/java/com/aws/samples/opensearch/service/CustomerSearchService.java:85:17
java: cannot access org.springframework.data.elasticsearch.core.query.BaseQueryBuilder
  class file for org.springframework.data.elasticsearch.core.query.BaseQueryBuilder not found

**Comment by Neuw84** [comment]
Hi, 

Update the code from the latest versions. However, should be a thing from your side as I always test all the released versions.

Let me know!
